"""Analyze BLIP concept embeddings generated by SPUME extract_concepts.py."""
import csv, json, pickle
from collections import Counter, defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]

# Load SPUME BLIP output
vocab_path = ROOT / "datasets/metashift/blip_extracted_concepts_0_0_vocab.pickle"
emb_path = ROOT / "datasets/metashift/blip_extracted_concepts_0_0_img_embeddings.pickle"
keys_path = ROOT / "datasets/metashift/blip_extracted_concepts_0_0_img_embedding_keys.pickle"
meta_path = ROOT / "datasets/metashift/metadata_metashift_catdog.csv"

with open(vocab_path, "rb") as f:
    vocab = pickle.load(f)
with open(emb_path, "rb") as f:
    embeddings = pickle.load(f)
with open(keys_path, "rb") as f:
    keys = pickle.load(f)

meta_rows = list(csv.DictReader(open(meta_path)))
train_rows = [r for r in meta_rows if r["split"] == "train"]

# Build key lookup
def norm(p):
    return str(p).strip().replace("\\", "/")
img_key_map = {norm(r["img_path"]): (r["class_name"], r["context_name"]) for r in train_rows}

# Match
class_concept = defaultdict(Counter)
overall = Counter()
matched = 0
for key, emb in zip(keys, embeddings):
    k = norm(key)
    if k in img_key_map:
        cls, ctx = img_key_map[k]
        active = emb == 1
        for i in range(len(vocab)):
            if active[i]:
                concept = vocab[i]
                overall[concept] += 1
                class_concept[cls][concept] += 1
        matched += 1

print(f"BLIP-large concept extraction results")
print(f"  Train rows: {len(train_rows)}")
print(f"  Matched keys: {matched}")
print(f"  Vocab size: {len(vocab)}")
print(f"  Total tokens: {sum(overall.values()):,}")
print(f"  Unique concepts: {len(overall)}")

print(f"\nTop-20 overall:")
for w, c in overall.most_common(20):
    print(f"  {w:25s} {c:6d}")

for cls in ["cat", "dog"]:
    print(f"\nTop-15 for {cls}:")
    for w, c in class_concept[cls].most_common(15):
        print(f"  {w:25s} {c:6d}")

# Save summary
summary = {
    "model": "BLIP-large",
    "total_train": matched,
    "vocab_size": len(vocab),
    "top_overall": [[w, c] for w, c in overall.most_common(50)],
    "top_per_class": {c: [[w, n] for w, n in ctr.most_common(20)] for c, ctr in class_concept.items()},
}
out = ROOT / "analysis/metashift/blip_concept_summary.json"
with open(out, "w") as f:
    json.dump(summary, f, indent=2, ensure_ascii=False)
print(f"\nSummary saved to: {out}")
