!!python/object/new:easydict.EasyDict
dictitems:
  alpha: 1.0
  amp: true
  augmentation: true
  backbone: resnet50
  batch_size: 8
  blip_attr_embed_path: D:\SPUME\datasets\metashift\blip_extracted_concepts_0_0_img_embeddings.pickle
  blip_vocab_path: D:\SPUME\datasets\metashift\blip_extracted_concepts_0_0_vocab.pickle
  config_file: ../configs/metashift/metashift_catdog_blip_spume_full.yaml
  data_folder: D:\SPUME\datasets\metashift
  dataset: metashift_catdog
  fast_train: false
  lr: 0.001
  meta_chunk_size: 2
  metadata_path: D:\SPUME\datasets\metashift\metadata_metashift_catdog.csv
  n_classes: 2
  n_gpu: 1
  num_episode: 80
  num_epochs: 50
  num_query: 10
  num_supp: 10
  num_workers: 4
  pretrained: true
  random_sampler: false
  save_folder: D:\SPUME\how_to_run\meta_spurious_exprs
  scheduler: cosine
  score_func: tanh-abs-log
  seed: 100
  tag: metashift_catdog_blip_spume_full
  task_num: 1
  temp: 5.0
  test: false
  topk: 10
  use_checkpoint: true
  use_group_label: false
  use_val: true
  val_threshold_num: 100
  vit_gpt2_attr_embed_path: D:\SPUME\datasets\metashift\blip_extracted_concepts_0_0_img_embeddings.pickle
  vit_gpt2_vocab_path: D:\SPUME\datasets\metashift\blip_extracted_concepts_0_0_vocab.pickle
  vlm: blip
state:
  alpha: 1.0
  amp: true
  augmentation: true
  backbone: resnet50
  batch_size: 8
  blip_attr_embed_path: D:\SPUME\datasets\metashift\blip_extracted_concepts_0_0_img_embeddings.pickle
  blip_vocab_path: D:\SPUME\datasets\metashift\blip_extracted_concepts_0_0_vocab.pickle
  config_file: ../configs/metashift/metashift_catdog_blip_spume_full.yaml
  data_folder: D:\SPUME\datasets\metashift
  dataset: metashift_catdog
  fast_train: false
  lr: 0.001
  meta_chunk_size: 2
  metadata_path: D:\SPUME\datasets\metashift\metadata_metashift_catdog.csv
  n_classes: 2
  n_gpu: 1
  num_episode: 80
  num_epochs: 50
  num_query: 10
  num_supp: 10
  num_workers: 4
  pretrained: true
  random_sampler: false
  save_folder: D:\SPUME\how_to_run\meta_spurious_exprs
  scheduler: cosine
  score_func: tanh-abs-log
  seed: 100
  tag: metashift_catdog_blip_spume_full
  task_num: 1
  temp: 5.0
  test: false
  topk: 10
  use_checkpoint: true
  use_group_label: false
  use_val: true
  val_threshold_num: 100
  vit_gpt2_attr_embed_path: D:\SPUME\datasets\metashift\blip_extracted_concepts_0_0_img_embeddings.pickle
  vit_gpt2_vocab_path: D:\SPUME\datasets\metashift\blip_extracted_concepts_0_0_vocab.pickle
  vlm: blip
